# Generated by Django 3.0.4 on 2020-04-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('meetingWith', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('userId', models.IntegerField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
