# Generated by Django 3.0.4 on 2020-04-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='summery',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
